Mission9/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission9.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission9.Controllers
{
    public class PurchaseController : Controller
    {
        //Instantiates basket
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }
        public PurchaseController(IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }
        //the get response for the Checkout
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }
        //the post response for the checkout
        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empyt!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Mission9/Pages/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission9.Infrastructures;
using Mission9.Models;

namespace Mission9.Pages
{
    public class AddModel : PageModel
    {
        // Model to allow a user to add a book to their cart. Includes getter and setter for the repository, initializes the repository, creates an instance of a basket, gets and sets the return url, 
        // has functionality on get to populate the page with data related to the basket passed, and when it posts the data, it takes them back to the url they were just on. 
        private IMission9Repository repo { get; set; }
        public AddModel (IMission9Repository temp, Basket bk)
        {
            repo = temp;
            basket = bk;
        }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);
            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Mission9/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission9.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission9/Pages/Add.cshtml
@page
@model Mission9.Pages.AddModel
@{
}
@*Table to show the information in the cart. It is brought in dynamically through the basket which gets reset every time you end a session. *@
<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var i in Model.basket.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>
                    <td>@i.Quantity</td>
                    <td>$@i.Book.Price</td>
                    <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="bookId" value="@i.Book.BookId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
    </tbody>
    @*Row in table to show total cost. Converts string to currency. *@
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>
@*Button to allow users to continue shopping. Button to allow users to submit cart that then shows up in database.*@
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Mission9/Pages/PurchaseCompleted.cshtml
@page
@model Mission9.Pages.PurchaseCompletedModel
@{
}
@*Confirmation page*@
<div class="text-center">
    <h2>Thank you for your order!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Mission9/Pages/_AddLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    @* This is a new layout page for the page where the cart is kept *@
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">BOOK STORE</div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>