Mission9/Components/BasketSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission9.Models;
namespace Mission9.Components
{
    public class BasketSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public BasketSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }
        //Don't remember what this does tbh
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Mission9/Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission9.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission9.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private IMission9Repository repo { get; set; }
        public CategoriesViewComponent (IMission9Repository temp)
        {
            repo = temp;
        }
        //Creates view bag for the categories
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Mission9/Views/Shared/BooksSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
@model Book
@*Div that will contain the cards for each of the books. The data is brought in dynamically through the model for each book. The book id is taken when you click on a book to populate the add view with the correct
    information.*@
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">Publisher: @Model.Publisher | ISBN: @Model.ISBN | Classification: @Model.Classification | Category: @Model.Category | Page Count: @Model.PageCount
        <form method="post" asp-page="/Add">

            <input type="hidden" asp-for="@Model.BookId"/>
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>

            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm float-end">Add Book to Cart</button>
            </span>
        </form>
    </div>
</div>
@*Style tag to change card color*@

<style>
    .card {
        transition: background-color 0.3s ease-in-out;
    }

    .card:hover {
        background-color: #000;
        transition: background-color 0.3s ease-in-out;
    }

    .card-title,
    .card-text {
        transition: color 0.3s ease-in-out;
    }

    .card:hover .card-title,
    .card:hover .card-text {
        color: #fff;
        transition: color 0.3s ease-in-out;
    }
    .card:hover h4{
        color: #fff;
    }
</style>

Mission9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission9</title>
    @*bringing in bootstrap and custom css. *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*Creating a nav bar and partitioning the page into parts between the list of books and the category filtering menu. *@
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="bg-dark text-white p-2">
                    <span class="navbar-brand ml-2">BOOK STORE</span>
                </div>    
                @*Including the cart icon*@
                <div class="col-6 text-right">
                    <vc:basket-summary />
                </div>
            </div>
        </div>
    </div>
    
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:categories></vc:categories>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>